# Generated by Django 6.0.6 on 2026-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_authlog_passwordhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signup_ip_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
